### ISSUE TITLE
Question: how to access to key that has dot in names?

### ISSUE THREAD

**Issue by gdbtek** [mickhansen/dottie.js#17]
if a key has dot in name, how do I access to it?

```
var values = {
  some: {
    'nested.with.dot': {
        key: 'foobar';
    }
  }
}

dottie.get(values, 'some.nested.with.dot.key');
```

**Comment by mickhansen** [comment]
That's not supported right now i'm afraid.
Not sure how it would work, i suppose we would need some different way of saying that these dots are literal dots and not seperators.

**Comment by mickhansen** [comment]
An alternate syntax like `dottie.get(values, ['some', 'nested.with.dot', 'key'])` could probably do the trick.

**Comment by gdbtek** [comment]
awesome! Thanks @mickhansen

**Comment by domarmstrong** [comment]
Any chance of re-opening this as a feature request. I use dottie for fields filtering on objects, and I don't know if a user is asking for ['foo', 'bar.baz'] to be able to split it up, its down to whats in the data.

User says:
```
'foo.bar.baz'
```
Data has:
```
{ foo: { 'bar.baz': true } }
```

All I can do is just `dotties.get(data, 'foo.bar.baz')`.

I guess it could be unclear if you mean:
{ 'foo.bar': { 'baz': true } }
{ 'foo.bar.baz': true }

I'd probably declare that if { 'foo.bar.baz' } exists then that path is used.

**Comment by mickhansen** [comment]
@domarmstrong Please open a new issue describing your usecase in more detail with examples (i'm not quite sure i get it).

This issue was resolved by providing set/get via array
