### ISSUE TITLE
dottie vs dotty - compatibility

### ISSUE THREAD

**Issue by Redsandro** [mickhansen/dottie.js#19]
Is this originally a fork from https://github.com/deoxxa/dotty ?
Is it backwards compatible?

**Comment by mickhansen** [comment]
It is not, i think i authored this library a few days before dotty.
I'm not sure about compatability, looking at dotty's get syntax i think it's mostly compatable yes.

**Comment by Redsandro** [comment]
This library is interesting purely from the fact that you are responding. :smile: I've been stuck using a custom version of `dotty` since my [PR](https://github.com/deoxxa/dotty/pull/10) didn't see anything besides tumbleweed.

How does `dottie` handle setting a value in.a.path.that doesn't exist?

I would like be able to either overwrite a value if the path exists only, not overwrite a value, or create the entire path if it doesn't exist.

**Comment by mickhansen** [comment]
Dottie is still actively maintained, sort of :) Atleast i respond to issues and i just recently did some performance enhancement commits.

Currently it will create the nested object structure needed to set. I'm open to supporting a set of options for dottie.set

**Comment by henrikhaugboelle** [comment]
Just pitching in to establish reliability. Dottie.js is furthermore used in
several production-level projects, so a few of us are reliant upon it and
will therefore pitch in when (if) necessary.

**Comment by Redsandro** [comment]
@henrikhaugboelle yeah same here, that's why I'm looking to move away from `dotty`. Nice to know. I'll star this project for now.

**Comment by Redsandro** [comment]
@mickhansen sorry for the small delay. I've added the small but important force function here: https://github.com/mickhansen/dottie.js/pull/20
