### ISSUE TITLE
Getting paths with dots in some keys

### ISSUE THREAD

**Issue by domarmstrong** [mickhansen/dottie.js#23]
I use dottie for user defined dynamic filtering on objects. I understand that there is a feature to use arrays of keys to handle path lookup like `dotties.get(data, ['foo', 'bar.baz'])`.
However I don't know if a user is asking for ['foo', 'bar.baz'] or ['foo.bar', 'baz']. That is determined by the data that they are looking at.

For example:

User says:

```
'foo.bar.baz'
```

Data has:

```
{ foo: { 'bar.baz': true } }
```

All I can do is `dotties.get(data, 'foo.bar.baz')` because I do not know what the data is. So it would be great if dottie could handle this.

It could be unclear with a situation like:

```
{
  foo: { 'bar.baz': true },
  'foo.bar': { baz: true },
  'foo.bar.baz: true,
}
```

In this case I'd probably declare that if { 'foo.bar.baz' } exists then that path is used.

It may introduce an overhead in the library so it may need to be 'enabled' with an option? If I asked for 'foo.bar.baz' you would always need to check for 'foo.bar.baz' then 'foo.bar' then 'foo' etc.

I could handle this myself, but I do already use dottie in several places and really like it ;)

**Comment by janmeier** [comment]
Supposing `transform` was made recursive, you could do that first, and then use a regular `get`. Of course this can be heavy if the object is large, but so would checking all possible paths be

**Comment by domarmstrong** [comment]
I do actually use transform.

```
/**
 * Handle the ?fields query string parameter
 * @param data {Object|Array}
 * @param fields {String}
 */
function fields(data, fields) {
  if (!fields) return data;

  // ?fields=foo,bar.baz filtering
  function filter(item) {
    let dottieTransform = {};
    fields.split(',').forEach(field => {
      let value = dottie.get(item, field);
      if (value !== undefined) {
        dottieTransform[field] = value;
      }
    });
    return dottie.transform(dottieTransform);
  }

  if (Array.isArray(data)) {
    return data.map(filter);
  }

  return filter(data);
}
```

**Comment by janmeier** [comment]
I was thinking of extending transform to also convert `{ foo: { 'bar.baz': true } }` into `{ foo: { bar: { baz: true }}}` - Currently it only transforms the top layer (foo). Then you would be able to use get. Perhaps adding a `recursive` flag to transform
