### ISSUE TITLE
transform wont work for array paths

### ISSUE THREAD

**Issue by sushantdhiman** [mickhansen/dottie.js#29]
Say I have a path like `object.edges[0].node`, if I try to use `transform` on that it will generate an object like this

```js
{
  object: {
    'edges[0]': {
      node: undefined
    }
  }
}
```

I think it should take care of arrays as well and generate structure like this

```js
{
  object: {
    'edges': [{
      node: undefined
    }]
  }
}
```

**Comment by mickhansen** [comment]
I don't think Dottie has much array logic at all.
`lodash' probably accomplishes most of what this library does nowadays

**Comment by sushantdhiman** [comment]
I have used `lodash.set` to get around this issue for now

```js
set({}, 'object.edges[0].node', undefined)
```

This issue is not blocking but just wanted to report that array paths are not transformed
